import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, it } from "node:test";
import { CONTRACT_ADDRESSES, resolveContractAddresses } from "../lib/addresses";

/**
 * The committed address book (#61), held to its sources of truth.
 *
 * The table's job is to stop a build pointed at a public chain from silently
 * reading a local-skeleton address, so the tests here are about the two ways it
 * could fail at that job: an entry drifting from the published deployment record,
 * and the resolver quietly falling back where it should refuse.
 *
 * The testnet entry is compared against `docs/deployments/robinhoodTestnet.md`
 * rather than against a copy of the same literals, because a test whose both sides
 * come from the test asserts nothing - the repo has shipped that defect more than
 * once. The deployment record is generated by `verify-and-publish.ts` from the
 * chain itself, which makes it the closest committed artefact to the truth.
 */

const DEPLOYMENT_RECORD = fileURLToPath(
  new URL("../../../docs/deployments/robinhoodTestnet.md", import.meta.url),
);

/** Pull a contract's address out of the deployment record's markdown table. */
function recordedAddress(source: string, contract: string): string {
  // A table row like: | `RushoodGame` | [`0x...`](https://...) | verified |
  const row = new RegExp("^\\|\\s*`" + contract + "`\\s*\\|\\s*\\[`(0x[0-9a-fA-F]{40})`\\]", "m");
  const match = source.match(row);
  assert.ok(match, `deployment record has no table row for ${contract}`);
  return match[1];
}

describe("committed address book (#61)", () => {
  const record = readFileSync(DEPLOYMENT_RECORD, "utf8");

  it("keeps the 46630 entry identical to the published deployment record", () => {
    // The chain id is parsed out of the record's heading rather than restated, so
    // even the entry's key is held to the record.
    const heading = record.match(/^# RUSHOOD deployment - \w+ \(chain (\d+)\)/);
    assert.ok(heading, "deployment record has no parseable heading");
    const entry = CONTRACT_ADDRESSES[Number(heading[1])];
    assert.ok(entry, `no committed entry for chain ${heading[1]}`);
    assert.equal(entry.game, recordedAddress(record, "RushoodGame"));
    assert.equal(entry.rush, recordedAddress(record, "Rushood"));
  });

  it("keeps the 31337 entry at the deterministic skeleton addresses", () => {
    assert.deepEqual(CONTRACT_ADDRESSES[31337], {
      game: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      rush: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    });
  });

  it("has no mainnet entry, because no mainnet deployment exists", () => {
    // If this fails because a mainnet deployment now exists, add the entry from its
    // deployment record and compare against that record above, as 46630 does.
    assert.equal(CONTRACT_ADDRESSES[4663], undefined);
  });
});

describe("address resolution (#61)", () => {
  it("resolves a committed chain with no env at all", () => {
    assert.deepEqual(resolveContractAddresses(46630, {}), CONTRACT_ADDRESSES[46630]);
  });

  it("lets an explicit env override win over the committed entry, per address", () => {
    const game = "0x0000000000000000000000000000000000000001";
    const resolved = resolveContractAddresses(46630, { game });
    assert.equal(resolved.game, game);
    assert.equal(resolved.rush, CONTRACT_ADDRESSES[46630].rush);
  });

  it("treats the empty string and whitespace as unset, so a shell can suppress a .env override", () => {
    assert.deepEqual(
      resolveContractAddresses(46630, { game: "", rush: "  " }),
      CONTRACT_ADDRESSES[46630],
    );
  });

  it("trims an override before validating it", () => {
    const rush = "0x0000000000000000000000000000000000000002";
    assert.equal(resolveContractAddresses(31337, { rush: ` ${rush}\n` }).rush, rush);
  });

  it("refuses a malformed override, naming the variable", () => {
    assert.throws(
      () => resolveContractAddresses(46630, { game: "0xnot-an-address" }),
      /NEXT_PUBLIC_GAME_ADDRESS is not a valid address/,
    );
  });

  it("never falls back to another chain's entry: an unknown chain with no env fails loudly", () => {
    assert.throws(
      () => resolveContractAddresses(4663, {}),
      (error: Error) => {
        assert.match(error.message, /chain 4663/);
        assert.match(error.message, /NEXT_PUBLIC_GAME_ADDRESS/);
        assert.match(error.message, /NEXT_PUBLIC_RUSH_ADDRESS/);
        // The failure must not smuggle the local skeleton in as a suggestion.
        assert.doesNotMatch(error.message, /0x9fE46736/);
        return true;
      },
    );
  });

  it("on an unknown chain, a partial override still fails, naming only what is missing", () => {
    assert.throws(
      () => resolveContractAddresses(4663, { game: "0x0000000000000000000000000000000000000003" }),
      (error: Error) => {
        assert.match(error.message, /NEXT_PUBLIC_RUSH_ADDRESS/);
        assert.doesNotMatch(error.message, /NEXT_PUBLIC_GAME_ADDRESS is not set/);
        return true;
      },
    );
  });

  it("reports every problem at once, loadRelayerConfig style", () => {
    assert.throws(
      () => resolveContractAddresses(4663, { game: "bad" }),
      (error: Error) => {
        assert.match(error.message, /NEXT_PUBLIC_GAME_ADDRESS is not a valid address/);
        assert.match(error.message, /NEXT_PUBLIC_RUSH_ADDRESS is not set/);
        return true;
      },
    );
  });
});

describe("module-scope resolution", () => {
  it("contracts.ts re-exports the resolved addresses for the configured chain", async () => {
    // The unit suite runs with no NEXT_PUBLIC_CHAIN_ID, so the configured chain is
    // the local skeleton; the constants every consumer imports must be the address
    // book's entry for it.
    const { GAME_ADDRESS, RUSH_ADDRESS } = await import("../lib/contracts");
    assert.equal(GAME_ADDRESS, CONTRACT_ADDRESSES[31337].game);
    assert.equal(RUSH_ADDRESS, CONTRACT_ADDRESSES[31337].rush);
  });
});
